version: 0.1

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install
  post_build:
    commands:
      - echo Build completed!
      - echo "Updating lambda Function..."
      - aws lambda update-function-code --function-name github-to-lambda-demo --zip-file fileb://target/notes-store-data-1.0-SNAPSHOT.jar
      - echo Updated AWS
artifacts:
  files:
    - target/notes-store-data-1.0-SNAPSHOT.jar